name: Commit Message Check

on:
  push:
    branches:
      - main  # Adjust this to your default branch if it's not 'main'
  pull_request:
    branches:
      - main  # Adjust this to your default branch if it's not 'main'

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Check commit message
        id: check_commit
        run: |
          #!/bin/bash
          
          # Get the commit message
          if [ "\${{ github.event_name }}" == "pull_request" ]; then
            COMMIT_MESSAGE="\${{ github.event.pull_request.title }}"
          else
            COMMIT_MESSAGE=\$(git log -1 --pretty=%B)
          fi
          
          # Define the prefixes
          PREFIXES=("feat:" "fix:" "docs:" "chore:" "style:" "refactor:" "test:")

          # Check if the commit message starts with one of the prefixes
          VALID_PREFIX=false
          for PREFIX in "\${PREFIXES[@]}"; do
            if [[ "\$COMMIT_MESSAGE" == "\$PREFIX"* ]]; then
              VALID_PREFIX=true
              break
            fi
          done

          if [ "\$VALID_PREFIX" = false ]; then
            echo "Commit message does not start with a valid prefix."
            exit 1
          fi

          # Check if the commit message is at least 5 words long
          WORDS=\$(echo "\$COMMIT_MESSAGE" | awk '{print NF}')
          if [ "\$WORDS" -lt 5 ]; then
            echo "Commit message is too short. It must contain at least 5 words."
            exit 1
          fi

          echo "Commit message is valid."
